### ISSUE TITLE
demo site does not display "pages"

### ISSUE THREAD

**Issue by schettino72** [getnikola/comet_cms#39]
I created a "page" but it seems there is no link that leads me to the page.

Also it would be nice to have a link from the edit page that leads me directly to the live site on the page/post being edited.

**Comment by Kwpolska** [comment]
I would have to install the navstories plugin or link to the STORY_INDEX. Will do in 8 days (on vacation now)

## 

Chris Warrick https://chriswarrick.com

**Comment by Kwpolska** [comment]
Fixed with STORY_INDEX.
