### ISSUE TITLE
pyinotify necessary for coil?

### ISSUE THREAD

**Issue by carlkl** [getnikola/comet_cms#41]
pyinotify is not available for Windows and has to be excluded manually from requirements.txt before install. I cannot find any reference to pynotify in the code as well. It should be removed IMHO.

**Comment by Kwpolska** [comment]
That is/was a doit dependency on Linux. I'll remove that and clean up the
requirements file tomorrow.

## 

Chris Warrick https://chriswarrick.com/

**Comment by Kwpolska** [comment]
fixed in v1.3.8 (and typed wrong number in commit message)
