### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by davidak** [getnikola/comet_cms#44]
![bildschirmfoto 2016-02-27 um 21 10 58](https://cloud.githubusercontent.com/assets/91113/13375092/ec11002e-dd96-11e5-9720-7ec5f51fbb34.png)

Coil CMS v1.3.8
Python 3.5.1
OS X 10.10

**Comment by Kwpolska** [comment]
Have you built the site at least once, as the setup guide says?

**Comment by davidak** [comment]
Yes, before i installed Coil.
I done it again but didn't help.

**Comment by davidak** [comment]
I setup a new site and it works.
maybe some old cache...
