### ISSUE TITLE
No support for custom theme

### ISSUE THREAD

**Issue by dpaleino** [getnikola/comet_cms#49]
Hello,

if I have a custom theme inheriting from bootstrap3 or bootstrap3-jinja, Coil does not recognize it. This is because _site.THEMES stores fullpaths -- at least in my case, where I have everything inside a virtualenv.

Instead, stripping all but the last path components, gives the desired result.

**Comment by Kwpolska** [comment]
Please open a pull request again, this time against getnikola/coil. (Thanks for fixing this so quickly!)
