### ISSUE TITLE
Both demo sites are gone?

### ISSUE THREAD

**Issue by hartwork** [getnikola/comet_cms#51]
None of these websites mentioned at https://coil.readthedocs.io/ seem to respond to HTTP:
* https://coildemo-site.getnikola.com/
* https://coildemo-admin.getnikola.com/

Could be related to #47?

**Comment by Kwpolska** [comment]
The demo site was closed recently because we’ve lost interest in Coil. We recommend other CMSes: https://getnikola.com/blog/a-cms-or-two-for-nikola-dato-cms-and-netlify-cms-integration.html

I’ll update the docs soon.

**Comment by hartwork** [comment]
:+1: for the patch
